query allGeneralSearch($search: String) {
    allGeneralSearch(search: $search) {
        nodes {
            id
            name
            classByClassId {
                name
            }
        }
    }
}