query charactersLessThanHeight($height: Int = 135) {
  allHeightCharacter(charHeight: $height) {
    nodes {
      id
      name
    }
  }
}

query allRaceCharacter($race: String) {
  allRaceCharacter(search: $race) {
    nodes {
      id
      name
    }
  }
}

query allCharacter($search: String) {
  allCharacters(condition: { name: $search }) {
    nodes {
      id
      name
      classByClassId {
        name
      }
    }
  }
}

query getOperatorDetails($name: String!) {
  characterByName(name: $name) {
    name
    gender
    height
    placeOfBirthByPlaceOfBirthId {
      name
    }
    raceByRaceId {
      name
    }
    infectionByInfectionId {
      name
    }
    classByClassId {
      name
    }
    branchByBranchId {
      name
    }
    characterArtistsByCharacterId {
      nodes {
        artistByArtistId {
          name
        }
      }
    }
  }
}
