query charactersLessThanHeight($height: Int = 135) {
  allHeightCharacter(charHeight: $height) {
    nodes {
      id
      name
    }
  }
}

query allRaceCharacter($race: String) {
  allRaceCharacter(search: $race) {
    nodes {
      id
      name
    }
  }
}

query allCharacter($search: String) {
  allCharacters(condition:  {
     name: $search
  }) {
    nodes {
      id
      name
    }
  }
}