query orCharacters(
  $class: [String!]!
  $place: [String!]!
  $race: [String!]
  $infection: [String!]!
  $branch: [String!]!
  $gender: [String!]!
  $artist: [String!]!
  $rarity: [BigFloat!]!
) {
  orPlacesOfBirth(ops: $place) {
    nodes {
      name
      classByClassId {
        name
      }
    }
  }
  orRaces(ops: $race) {
    nodes {
      name
      classByClassId {
        name
      }
    }
  }
  orInfections(ops: $infection) {
    nodes {
      name
      classByClassId {
        name
      }
    }
  }
  orClasses(ops: $class) {
    nodes {
      name
      classByClassId {
        name
      }
    }
  }
  orBranches(ops: $branch) {
    nodes {
      name
      classByClassId {
        name
      }
    }
  }
  orGenders(ops: $gender) {
    nodes {
      name
      classByClassId {
        name
      }
    }
  }
  orArtists(ops: $artist) {
    nodes {
      name
      classByClassId {
        name
      }
    }
  }
  orRarity(search: $rarity) {
    nodes {
      rarity
      name
      classByClassId {
        name
      }
    }
  }
}
